spring:
  application:
    name: tenants-manage-java
  datasource:
    url: ${DB_TENANTS_URL}
    username: ${DB_TENANTS_USERNAME}
    password: ${DB_TENANTS_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8081