spring:
  application:
    name: tenants-manage-java
  datasource:
    url: jdbc:postgresql://localhost:5432/tenants-db
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081