server:
  servlet:
    context-path: /api
spring:
  application:
    name: products-management
  jackson:
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-prefix: ${JWT_PREFIX_KEY}
  token-header: Authorization
  expiration-time: 3600000
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    acess-key: ${S3_ACESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region-static: ${S3_REGION_STATIC}
tenant:
  service:
    url: ${TENANT_SERVICE_URL}