server:
  servlet:
    context-path: /api
spring:
  application:
    name: products-management
  jackson:
    serialization:
      indent-output: true
  jpa:
    driver-class-name: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/tenants-db
    username:
    password:
    driver-class-name: org.postgresql.Driver
jwt:
  secret-key: 3aa15421-55d3-48f2-8372-ddca66362e98
  token-prefix: Bearer
  token-header: Authorization
  expiration-time: 3600000
aws:
  s3:
    bucket-name:
    acess-key:
    secret-key:
    region-static: