server:
  servlet:
    context-path: /api
spring:
  application:
    name: products-management
  jackson:
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  cache:
    type: redis
jwt:
  secret-key: 3aa15421-55d3-48f2-8372-ddca66362e98
  token-prefix: Bearer
  token-header: Authorization
  expiration-time: 3600000
aws:
  s3:
    bucket-name:
    acess-key:
    secret-key:
    region-static:
tenant:
  service:
    url: ${TENANT_SERVICE_URL}:http://localhost:8081/tenants